/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vnwnpwsjgoequitxivvm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZud25wd3NqZ29lcXVpdHhpdnZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MjkzMTksImV4cCI6MjA3NjQwNTMxOX0.yhc9Zf_VpdDbJYDVlubL5-e2mu7O2GiA-54qJWc-qV4"